server:
  port: 9091

springdoc:
  swagger-ui:
    path: /swagger.html
    enabled: false

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:customer
    username: sa
    password: qwerty
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

custom:
  activeprofileName: Production Profile

