server:
  port: 9092
springdoc:
  swagger-ui:
    path: /swagger.html
    enabled: false
spring:
  application:
    name: businessdomain-transaction
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:transaction
    username: sa
    password: qwerty
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
custom:
  activeprofileName: Porduction Profile
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    healthcheck:
      enabled: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: "*"