server:
  port: 9092
# swagger-ui custom path
springdoc:
  swagger-ui:
   path: /swagger.html
   enabled: false

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:transaction
    username: sa
    password: 123456
  h2:
    console:
      enabled: true