server:
  port: 9090

springdoc:
  swagger-ui:
    path: /swagger.html
    enabled: false

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:customer
    username: sa
    password: 123456
  h2:
    console:
      enabled: true