server:
  port: 9090
# swagger-ui custom path
springdoc:
  swagger-ui:
   path: /swagger.html
   enabled: false

spring:
  profiles:
    active: prod
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:men:customer
    username: sa
    password: 123456
  h2:
    console:
      enabled: true